apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  # TODO: Set the number of replicas (try 3 for high availability)
  # replicas: 
  selector:
    matchLabels:
      # TODO: Define selector labels
      # app: 
  template:
    metadata:
      labels:
        # TODO: Define pod labels (must match selector above)
        # app: 
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          # TODO: Configure WordPress database connection environment variables
          # env:
          #   - name: WORDPRESS_DB_HOST
          #     value: "mysql"
          #   - name: WORDPRESS_DB_USER
          #     value: "root"
          #   - name: WORDPRESS_DB_PASSWORD
          #     value: "password"
          ports:
            # TODO: Define the WordPress container port (HTTP uses port 80)
            # - containerPort: 