services:
  # Application stack from previous section
  app:
    build: ../.
    environment:
      - DB_HOST=database
      - REDIS_HOST=cache
    depends_on:
      # TODO: Ensure app starts after database and cache
    networks:
      - app-network
      - monitoring

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: webapp
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    networks:
      - app-network

  cache:
    image: redis:7-alpine
    networks:
      - app-network

  # TODO Add monitoring services for prometheus and grafana

volumes:
  grafana_data:

networks:
  app-network:
  monitoring:
