services:
  app:
    build: ../.
    volumes:
      - ../:/app
    environment:
      - FLASK_DEBUG=1
      - PYTHONPATH=/app
    command: python -m debugpy --listen 0.0.0.0:5678 --wait-for-client app.py
    ports:
      # TODO: forward the ports required for App and Debugging

  # Debug tools
  adminer:
    image: adminer
    ports:
      # TODO: Forward the port from docker to the host
      # Adminer uses port 8080 by default
    environment:
      ADMINER_DEFAULT_SERVER: database

  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      # TODO: Forward the redis-commander port 8081 to the host
    environment:
      REDIS_HOSTS: local:cache:6379
