services:
  app:
    restart: always
    deploy:
      replicas: 2 # Production scaling with multiple instances
      resources:
        limits:
          memory: 512M
          cpus: "0.5"

  database:
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"

  nginx:
    restart: always
    ports:
      - "80:80" # Production nginx on port 80
